using System;
using System.Linq;
using System.Reflection;
using System.Runtime.Loader;
using Autodesk.Revit.Attributes;
using Autodesk.Revit.DB;
using Autodesk.Revit.UI;
using Scotec.Revit.Loader;
using {2};

namespace {0}
{{
    [Transaction(TransactionMode.Manual)]
    public class {1}Factory : IExternalCommand
    {{
        private readonly IExternalCommand _instance;

        public {1}Factory()
        {{  
            var contextName = "{3}";
            var currentAssembly = GetType().Assembly;

            if(string.IsNullOrEmpty(contextName))
            {{
				contextName = currentAssembly.GetName().Name;
			}}
            var context = AssemblyLoadContext.All.FirstOrDefault(c => c.Name == contextName);
            if (context == null)
			{{
                var resolver = new AssemblyDependencyResolver(currentAssembly.Location);
                context = new RevitAssemblyLoadContext(contextName, resolver);
			}}

            var assembly = context.LoadFromAssemblyPath(currentAssembly.Location);
            using var scope = AssemblyLoadContext.EnterContextualReflection(assembly);
            var types = assembly.GetTypes();
            var type = types.First(type => type.Name == "{1}");
            _instance = (IExternalCommand)Activator.CreateInstance(type);
        }}

        Result IExternalCommand.Execute(ExternalCommandData commandData, ref string message, ElementSet elements)
        {{
            using var scope = AssemblyLoadContext.EnterContextualReflection(_instance.GetType().Assembly);
            return _instance.Execute(commandData, ref message, elements);
        }}
    }}
}}
