using System;
using System.Linq;
using System.Runtime.Loader;
using Autodesk.Revit.Attributes;
using Autodesk.Revit.DB;
using Autodesk.Revit.UI;
using {2};

namespace {0}
{{
    [Transaction(TransactionMode.Manual)]
    public class {1}Factory : IExternalCommand
    {{
        private readonly IExternalCommand _instance;

        public {1}Factory()
        {{  
            var assembly = AddinLoadContext.Instance.LoadFromAssemblyPath(typeof({1}Factory).Assembly.Location);
            using var context = AssemblyLoadContext.EnterContextualReflection(assembly);
            var types = assembly.GetTypes();
            var type = types.First(type => type.Name == "{1}");
            _instance = (IExternalCommand)Activator.CreateInstance(type);
        }}

        Result IExternalCommand.Execute(ExternalCommandData commandData, ref string message, ElementSet elements)
        {{
                return _instance.Execute(commandData, ref message, elements);
        }}
    }}
}}
